apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
     app: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: $APP_NAME
        image: sneka/addressbook:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  labels:
      app: $APP_NAME
spec:
  selector:
    app: $APP_NAME
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer